version: '3.7'

services:
  web:
    build: ./lib_catalog
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./app/:/usr/scr/app
    ports:
      - "8000:8000"
    #env_file:
    #  - ./.env.dev
    depends_on:
      - db
    network_mode: "service:db"

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django
    ports:
      - "8001:5432"
    mem_limit: 512m
    cpus: 0.5
#    network_mode: "service:web"
volumes:
  postgres_data:
