version: '3.7'

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./app/:/usr/scr/app
    ports:
      - 8000:8000
    #env_file:
    #  - ./.env.dev
    depends_on:
      - database
  database:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django

volumes:
  postgres_data:
